accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'acoounts'

urlpatterns=[

    path('signup/', views.signup_view, name='signup'),
    path('login/',views.login_view, name='login'),
    path('logout/',views.logout_view,name='logout'),
]

myDjangoStudyPlanner/urls.py
# from django.conf.urls import url
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    # /admin/
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('studyplanner/', include('studyplanner.urls')),
]

studyplanner/urls.py
from django.conf.urls import url
from django.urls import path

from studyplanner import views

app_name = 'studyplanner'
urlpatterns = [
    # /studyplanner/
    path('', views.IndexView.as_view(), name='index'),

    # path('', views.IndexView.as_view(), name='index'),

    # /studyplanner/id/
    # (id,method controller,name of template)
    path('<int:module_id>/', views.module_details, name='detail'),

    #/studyplanner/m_id/cw_id/
    path('<int:module_id>/<int:coursework_id>/', views.add_task, name='task_new'),

    # /studyplanner/m_id/cw_id/t_id/
     path('<int:module_id>/edit/<int:task_id>/', views.edit_task, name='edit_task'),

]

studyplanner/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse

class Semester(models.Model):
    semester_term = models.CharField(max_length=10)

    def __str__(self):
        return "Semester:%s" %(self.semester_term)


class Module(models.Model):
    semester = models.ForeignKey(Semester,on_delete=models.CASCADE)
    # id = models.IntegerField(primary_key=True)
    module_name = models.CharField(max_length=250)
    module_code = models.CharField(max_length=20)
    module_duration = models.CharField(max_length=20)

    def __str__(self):
        return "ID:%d      %s" % (self.id,self.module_name)

    def getCourseworks(self):
        courseworks = []
        for cw in Coursework.objects.all():
            if cw.module_id == self.id:
                if cw.cw_type == "cw":
                    courseworks.append(cw)
        return courseworks

    def getExams(self):
        exams = []
        for e in Coursework.objects.all():
            if e.module_id == self.id:
                if e.cw_type == "exam":
                    exams.append(e)
        return exams

    def getTasks(self):
        tasks = []
        for t in Task.objects.all():
            moduleid = t.coursework.module_id
            if moduleid == self.id:
                tasks.append(t)
        return tasks


class Coursework(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE,default="")
    # task = models.ForeignKey(Task,on_delete=models.CASCADE)
    # id = models.IntegerField(primary_key=True)
    cw_name = models.CharField(max_length=500)
    cw_date_set = models.DateField()
    cw_deadline = models.DateField()
    cw_weight = models.PositiveIntegerField()
    cw_type = models.CharField(max_length=10,default="")

    def __str__(self):
        return "ID:%s      %s" % (self.id,self.cw_name)

    def get_absolute_url(self):
        return reverse("studyplanner:detail",kwargs={"id":self.module.id})


class Task(models.Model):
    ACTIVITY_CHOICES = (
        (1, ("Studying")),
        (2, ("Programming")),
        (3, ("Writing")),
        (4, ("Analyse")),
        (5, ("Read"))
    )
    CRITERION_CHOICES=(
        (1,("Time Studied")),
        (2,("Chapters Covered")),
        (3,("Assignment completed")),
    )

    coursework = models.ForeignKey(Coursework, on_delete=models.CASCADE, default="")
    task_name = models.CharField(max_length=500)
    date_due = models.DateField()
    notes = models.CharField(default=" ",max_length=1000)
    time_that_will_be_spent = models.PositiveIntegerField(default=1)

    task_activity = models.IntegerField(choices=ACTIVITY_CHOICES,default=0)
    criterion_type = models.IntegerField(choices=CRITERION_CHOICES,default=0)
    requirement_criterion = models.PositiveIntegerField(default=1)
    readData = True

    def __str__(self):
        return "ID:%d   Task:%s"%(self.id,self.task_name)

    def get_absolute_url(self):
        return reverse("studyplanner:detail",kwargs={"id":self.id})

    def editTask(self, t):
        t = Task(t)

studyplanner/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.models import User
from django.forms import DateField

from .models import Task

from bootstrap_datepicker_plus import DatePickerInput

class TaskModelForm(forms.ModelForm):
    class Meta:
        model = Task
        fields=[
            'task_name','date_due','time_that_will_be_spent','task_activity',
            'criterion_type','requirement_criterion', 'notes',
        ]
        widgets = {
            'date_due': DatePickerInput(format='%Y-%m-%d'),  # specify date-frmat
        }

studyplanner/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, FormView

from .models import Semester, Module, Coursework, Task
from django.views import generic
from .forms import TaskModelForm
from .models import Task
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

# shows all the semesters
# def index(request):
#     all_modules = Module.objects.all()
#     context = { 'all_modules':all_modules}
#     return render(request,'studyplanner/index.html',context)
class IndexView(generic.ListView):
    template_name = 'studyplanner/index.html'
    context_object_name = 'all_modules'
    def get_queryset(self):
        all_modules = Module.objects.all()
        return all_modules


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskModelForm

    template_name =  'studyplanner/task_new.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(TaskCreateView, self).form_valid(form)



# shows all the courseworks of specified module
# in case the user is tring to access an invalid module with the module_id "/module_id/"
# it will throw an error 404 exeption
def module_details(request,module_id):
    if ('Back' in request.POST):
        print("BACK")
        return HttpResponseRedirect('/studyplanner/')
    if request.method == "POST":
        print("post")
    m = get_object_or_404(Module,pk = module_id)
    current_module = m.module_name
    current_code = m.module_code
    courseworks = m.getCourseworks()
    exams = m.getExams()
    tasks = m.getTasks()

    context = { 'courseworks':courseworks,
                'exams':exams,
                'current_module':current_module,
                'current_code':current_code,
                'm':m,
                'tasks':tasks,
                }
    return render(request,'studyplanner/detail.html',context)


def add_task(request,module_id,coursework_id):
    if ('Cancel' in request.POST):
        print("BACK")
        return HttpResponseRedirect('/studyplanner/' + str(module_id))

    if request.method == "POST":
        form = TaskModelForm(request.POST)
        if form.is_valid():
            t = Task()
            # saves a task object
            t.task_name = form.cleaned_data['task_name']
            t.date_due = form.cleaned_data['date_due']
            t.time_that_will_be_spent = form.cleaned_data['time_that_will_be_spent']
            t.task_activity = form.cleaned_data['task_activity']
            t.criterion_type = form.cleaned_data['requirement_criterion']
            t.notes = form.cleaned_data['notes']
            t.coursework = Coursework.objects.get(id = coursework_id)
            t.save()
            return HttpResponseRedirect('/studyplanner/'+str(module_id))
    else:
        form = TaskModelForm()
        module = Module.objects.get(pk=module_id)
        coursework = Coursework.objects.get(pk= coursework_id)
    return render(request,'studyplanner/task_new.html',{'form':form,'coursework':coursework,'module':module})

def edit_task(request, module_id, task_id):
    current_task = get_object_or_404(Task,pk=task_id)
    form = TaskModelForm(instance=current_task)

    if('Cancel' in request.POST):
        print("BACK")
        return HttpResponseRedirect('/studyplanner/' + str(module_id))

    if request.method =="GET":
        form = TaskModelForm(instance=current_task)
        return render(request, 'studyplanner/edit_task.html', {'edit_form': form})

    elif request.method == "POST":
        form = TaskModelForm(request.POST)
        if form.is_valid():
            print("change")
            t = Task.objects.get(pk = task_id)
            name = form.cleaned_data['task_name']
            date = form.cleaned_data['date_due']
            time = form.cleaned_data['time_that_will_be_spent']
            activity = form.cleaned_data['task_activity']
            criterion = form.cleaned_data['criterion_type']
            notes = form.cleaned_data['notes']
            if name != t.task_name:
                t.task_name = name
            if date != t.date_due:
                t.date_due=date
            if time != t.time_that_will_be_spent:
                t.time_that_will_be_spent==time
            if activity != t.task_activity:
                t.task_activity = activity
            if criterion != t.criterion_type:
                t.criterion_type = criterion
            if notes != t.notes:
                t.notes = notes
            t.save()
            return HttpResponseRedirect('/studyplanner/'+str(module_id))

templates/studyplanner/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<html>
<head>

<link  rel="stylesheet" href="{% static 'css/main.css' %}">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet">


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



    <title> study planner</title>

</head>

<body>
  <header>
  <div class="header">
      <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="/static/img/real.mp4" type="video/mp4">
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-3">StudyPlanner</h1>
        <p class="lead mb-0">blah blah</p>
      </div>
    </div>
  </div>
</div>
</header>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">



  <div class="collapse navbar-collapse" id="navbarNav">
    <a class="navbar-brand" href="/studyplanner">Home</a>
    <ul class="navbar-nav">
      <li class="nav-item active">
      <li class="nav-item">
        <a class="nav-link" href="#">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Profile</a>
      </li>
    </ul>
  </div>
</nav>
    <!-- <main role="main" class="container"> -->
      <div class="row">
        <div class="col-md-8">
          {%if messages %}

          {% endif %}
          {% block content %}{% endblock %}
        </div>
        </div>
    </main>
</body>
</html>

templates/studyplanner/detail.html
{% extends "studyplanner/base.html" %}
{% block content %}


<h1>{{ m.module_name }}<br>
{{ m.module_code }}</h1>

{% if courseworks or exams %}
    {{ "click assesment to add a task" }}<br>
{% endif %}

{% if courseworks %}
    <ul><br>
        {{ "Courseworks Deadlines" }}
        {% for cw in courseworks %}
            <li><a href="{% url 'studyplanner:task_new'  m.id cw.id%}">{{ cw.cw_name}} {{ "  Deadline: " }}{{ cw.cw_deadline }}</a></li>
        {% endfor %}

    </ul>
{% endif %}

{% if exams %}
    <ul><br>
        {{ "Exam Deadline" }}
        {% for e in exams %}
            <li><a href="{% url 'studyplanner:task_new'  m.id e.id%}">{{ e.cw_name}} {{ "  Date: " }}{{ e.cw_deadline }}</a></li>
        {% endfor %}
    </ul>
{% endif %}

{% if tasks %}
    <ul>
        {{ "Tasks" }}
        {% for t in tasks %}
            <li><a href="{% url 'studyplanner:edit_task'  m.id t.id%}">{{ t.task_name}}</a></li>
        {% endfor %}

    </ul>
{% endif %}

<form method="post">
    {% csrf_token %}<br>
    <button  type="submit"  name="Back" class="btn btn-success">Back</button>
</form>

{% endblock content %}

templates/studyplanner/edit_task.html
{% extends "studyplanner/base.html" %}

{% block content %}
<h1>{{ "EDIT TASK" }}</h1>

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% load crispy_forms_tags %}

<form  method="post">
    {% csrf_token %}
    {{ edit_form|crispy }}

    <button  type="submit"  class="btn btn-success">Save Task</button>

    <button  type="submit"  name="Cancel" class="btn btn-success">Cancel</button>
    </form>
{% endblock %}

templates/studyplanner/index.html
{% extends "studyplanner/base.html" %}
{% block content %}

<h1>Spring Semester</h1>

{% if all_modules %}
    <ul>
    {% for m in all_modules %}
        <li><a href="{% url 'studyplanner:detail' m.id%}">{{ "Module: " }}{{ m.module_name}}  {{ "Code: " }} {{ m.module_code }}  {{ "Duration: " }} {{ m.module_duration }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Modules available.</p>
{% endif %}

</body>
</html>
{% endblock content %}

templates/studyplanner/module.html
{% extends "studyplanner/base.html" %}

templates/studyplanner/task_new.html
{% extends "studyplanner/base.html" %}

{% block content %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}
{% load crispy_forms_tags %}

{% block main %}
<form  method="post">
    {% csrf_token %}<br>
    {{ "Module: " }}{{ module.module_name }}<br>
    {{ "Assingment: " }}{{ coursework.cw_name }}
    {{ form|crispy }}
    <button  type="submit"  name="Add Task" class="btn btn-success">Add Task</button>

</form>
    <form method="post">
        {% csrf_token %}<br>
        <button  type="submit"  name="Cancel" class="btn btn-success">Cancel</button>
    </form>
{% endblock %}
{% endblock content %}